config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations' }
root to: 'static_pages#home'
get '/about-us' => 'static_pages#about_us'


# dashboard
get '/dashboard' => 'dashboard#dashboard'
get '/dashboard-test' => 'dashboard#dashboard_test'
get '/yearly-report' => 'dashboard#yearly_report'
get '/monthly-report' => 'dashboard#monthly_report'
get '/weekly-dashboard-impressions' => 'dashboard#weekly_dashboard_impressions'
get '/weekly-dashboard-cost' => 'dashboard#weekly_dashboard_cost'
get '/weekly-dashboard-conversions' => 'dashboard#weekly_dashboard_conversions'
get '/weekly-dashboard-ctr' => 'dashboard#weekly_dashboard_ctr'
get '/weekly-dashboard-conversion-rate' => 'dashboard#weekly_dashboard_conversion_rate'
get '/weekly-dashboard-cpa' => 'dashboard#weekly_dashboard_cpa'
get '/weekly-dashboard-cpc' => 'dashboard#weekly_dashboard_cpc'
get '/dashboard-geo' => 'dashboard#dashboard_geographic'


get "login/prompt"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
require 'adwords_api'
before_action :authenticate_user!

  def dashboard
    @adwords_data = Report.new(current_user.adwords_id).download_criteria_report
    dashboard_report = DashboardHandler.new(@adwords_data)  
    campaigns_data_array =  dashboard_report.parse_report
    days_data_array = dashboard_report.parse_report_days
    
    @dashboard_kpi = DashboardKpi.new(days_data_array).package
    @cpa_recommendation = Recommendation.new(@dashboard_kpi[:cpa]).compare_cpa
    @ctr_recommendation = Recommendation.new(@dashboard_kpi[:cpa]).compare_ctr

    weekly_graph = Graph.new(@dashboard_kpi[:days], campaigns_data_array)
    @data = weekly_graph.make_graph_clicks
    @options = weekly_graph.options      
  end

  def weekly_dashboard_impressions
    @adwords_data = Report.new(current_user.adwords_id).download_criteria_report
    dashboard_report = DashboardHandler.new(@adwords_data)  
    campaigns_data_array =  dashboard_report.parse_report
    days_data_array = dashboard_report.parse_report_days

    @dashboard_kpi = DashboardKpi.new(days_data_array).package
    @cpa_recommendation = Recommendation.new(@dashboard_kpi[:cpa]).compare_cpa
    @ctr_recommendation = Recommendation.new(@dashboard_kpi[:cpa]).compare_ctr

    weekly_graph = Graph.new(@dashboard_kpi[:days], campaigns_data_array)
    @data = weekly_graph.make_graph_impressions
    @options = weekly_graph.options
  end


  def weekly_dashboard_cost
    @adwords_data = Report.new(current_user.adwords_id).download_criteria_report
    dashboard_report = DashboardHandler.new(@adwords_data)  
    campaigns_data_array =  dashboard_report.parse_report
    days_data_array = dashboard_report.parse_report_days

      
    @dashboard_kpi = DashboardKpi.new(days_data_array).package
    @cpa_recommendation = Recommendation.new(@dashboard_kpi[:cpa]).compare_cpa
    @ctr_recommendation = Recommendation.new(@dashboard_kpi[:cpa]).compare_ctr

    weekly_graph = Graph.new(@dashboard_kpi[:days], campaigns_data_array)
    @data = weekly_graph.make_graph_cost
    @options = weekly_graph.options
  end


  def weekly_dashboard_conversions
    @adwords_data = Report.new(current_user.adwords_id).download_criteria_report
    dashboard_report = DashboardHandler.new(@adwords_data)  
    campaigns_data_array =  dashboard_report.parse_report
    days_data_array = dashboard_report.parse_report_days
       
    @dashboard_kpi = DashboardKpi.new(days_data_array).package
    @cpa_recommendation = Recommendation.new(@dashboard_kpi[:cpa]).compare_cpa
    @ctr_recommendation = Recommendation.new(@dashboard_kpi[:cpa]).compare_ctr

    weekly_graph = Graph.new(@dashboard_kpi[:days], campaigns_data_array)
    @data = weekly_graph.make_graph_conversions
    @options = weekly_graph.options
  end

  def weekly_dashboard_ctr
    @adwords_data = Report.new(current_user.adwords_id).download_criteria_report
    dashboard_report = DashboardHandler.new(@adwords_data)  
    campaigns_data_array =  dashboard_report.parse_report
    days_data_array = dashboard_report.parse_report_days

    @dashboard_kpi = DashboardKpi.new(days_data_array).package
    @cpa_recommendation = Recommendation.new(@dashboard_kpi[:cpa]).compare_cpa
    @ctr_recommendation = Recommendation.new(@dashboard_kpi[:cpa]).compare_ctr

    weekly_graph = Graph.new(@dashboard_kpi[:days], campaigns_data_array)
    @data = weekly_graph.make_graph_ctr
    @options = weekly_graph.options           
  end


  def weekly_dashboard_conversion_rate
    @adwords_data = Report.new(current_user.adwords_id).download_criteria_report
    dashboard_report = DashboardHandler.new(@adwords_data)  
    campaigns_data_array =  dashboard_report.parse_report
    days_data_array = dashboard_report.parse_report_days
    
    @dashboard_kpi = DashboardKpi.new(days_data_array).package
    @cpa_recommendation = Recommendation.new(@dashboard_kpi[:cpa]).compare_cpa
    @ctr_recommendation = Recommendation.new(@dashboard_kpi[:cpa]).compare_ctr

    weekly_graph = Graph.new(@dashboard_kpi[:days], campaigns_data_array)
    @data = weekly_graph.make_graph_conv_rate
    @options = weekly_graph.options
  end

  def weekly_dashboard_cpa
      @adwords_data = Report.new(current_user.adwords_id).download_criteria_report
    dashboard_report = DashboardHandler.new(@adwords_data)  
    campaigns_data_array =  dashboard_report.parse_report
    days_data_array = dashboard_report.parse_report_days

  
   @dashboard_kpi = DashboardKpi.new(days_data_array).package
   @cpa_recommendation = Recommendation.new(@dashboard_kpi[:cpa]).compare_cpa
   @ctr_recommendation = Recommendation.new(@dashboard_kpi[:cpa]).compare_ctr

   weekly_graph = Graph.new(@dashboard_kpi[:days], campaigns_data_array)
   @data = weekly_graph.make_graph_cpa
   @options = weekly_graph.options

             
  end

  def weekly_dashboard_cpc
    @adwords_data = Report.new(current_user.adwords_id).download_criteria_report
    dashboard_report = DashboardHandler.new(@adwords_data)  
    campaigns_data_array =  dashboard_report.parse_report
    days_data_array = dashboard_report.parse_report_days

    @dashboard_kpi = DashboardKpi.new(days_data_array).package
    @cpa_recommendation = Recommendation.new(@dashboard_kpi[:cpa]).compare_cpa
    @ctr_recommendation = Recommendation.new(@dashboard_kpi[:cpa]).compare_ctr

    weekly_graph = Graph.new(@dashboard_kpi[:days], campaigns_data_array)
    @data = weekly_graph.make_graph_cpc
    @options = weekly_graph.options        
  end

def dashboard_test
    @data = {
        labels: ["January", "February", "March", "April", "May", "June", "July"],
        datasets: [
            {
                label: "Shoes",
                backgroundColor: "rgba(220,220,220,0.2)",
                borderColor: "rgba(220,220,220,1)",
                data: [65, 59, 80, 81, 56, 55, 40]
            },
            {
                label: "Shirtst",
                backgroundColor: "rgba(151,187,205,0.2)",
                borderColor: "rgba(151,187,205,1)",
                data: [28, 48, 40, 19, 86, 27, 90]
            }
        ]
        }
        @options = {
          :width => 1000,
         :height => 300,
         :scales => {
              :yAxes => [
                {:type => "linear", :id => "y-axis-1", :display => true, :position => "right"},
                {:type => "linear", :id => "y-axis-2", :display => true, :position => "left"}
           ]
         }
       } 
    

end


def dashboard_geographic
@adwords_data = download_criteria_report()
        data_hash = Hash.from_xml(@adwords_data)
        data_json = JSON.parse(data_hash.to_json)["report"]["table"]["row"]
      
      data_json.sort_by! do |item|
        item["day"]
      end

      campaigns = data_json.group_by{ 
        |object| Campaign.new(object['campaign']).clean_campaign
      }
            # ap campaigns
      campaigns_data_array = {}
      
      campaigns.each_with_index do |campaign, index|
      name = campaign[0]
      campaigns_data_array[name] = {}
        campaigns_data_array[name]["clicks_array"] = []         
        campaigns_data_array[name]["cost_array"] = []         
        campaigns_data_array[name]["conversions_array"] = []         
        campaigns_data_array[name]["impressions_array"] = []
        campaigns_data_array[name]["cpc_array"] = []
        campaigns_data_array[name]["conversion_rate_array"] = []
        campaigns_data_array[name]["cpa_array"] = []
        campaigns_data_array[name]["ctr_array"] = []
        
        campaign[1].each do |campaign_data_point|

              campaigns_data_array[name]["#{campaign_data_point['day']}"] = {
                clicks: campaign_data_point['clicks'].to_i,
                impressions: campaign_data_point['impressions'].to_i,
                cost: campaign_data_point['cost'].to_i,
                conversions: campaign_data_point['conversions'].to_i,
              }  
            
            campaigns_data_array[name]["impressions_array"].push campaigns_data_array[name]["#{campaign_data_point['day']}"][:impressions]
            campaigns_data_array[name]["conversions_array"].push campaigns_data_array[name]["#{campaign_data_point['day']}"][:conversions]
            campaigns_data_array[name]["clicks_array"].push campaigns_data_array[name]["#{campaign_data_point['day']}"][:clicks]
            campaigns_data_array[name]["cost_array"].push campaigns_data_array[name]["#{campaign_data_point['day']}"][:cost] / 1000000
            
            # manual operations
             if ((campaigns_data_array[name]["#{campaign_data_point['day']}"][:cost] / campaigns_data_array[name]["#{campaign_data_point['day']}"][:clicks]) rescue 0) == 0 
              p campaigns_data_array[name]["cpc_array"].push 0 
            else
              campaigns_data_array[name]["cpc_array"].push ((campaigns_data_array[name]["#{campaign_data_point['day']}"][:cost] / campaigns_data_array[name]["#{campaign_data_point['day']}"][:clicks])) / 1000000 rescue 0
            end

             if campaigns_data_array[name]["#{campaign_data_point['day']}"][:conversions] == 0
              campaigns_data_array[name]["conversion_rate_array"].push 0
             else
              campaigns_data_array[name]["conversion_rate_array"].push campaigns_data_array[name]["#{campaign_data_point['day']}"][:conversions].to_f / campaigns_data_array[name]["#{campaign_data_point['day']}"][:clicks].to_f rescue 0
            end
          
             if ((campaigns_data_array[name]["#{campaign_data_point['day']}"][:cost] / campaigns_data_array[name]["#{campaign_data_point['day']}"][:conversions]) rescue 0) == 0 
              campaigns_data_array[name]["cpa_array"].push 0 
            else
              campaigns_data_array[name]["cpa_array"].push ((campaigns_data_array[name]["#{campaign_data_point['day']}"][:cost] / campaigns_data_array[name]["#{campaign_data_point['day']}"][:clicks])) / 1000000 rescue 0
            end
              

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/dashboard.html.erb
<% if user_signed_in? %>
  <h1 class="dash-title">Hello <%= current_user.name %> Welcome to Your Dashboard:</h1>
    <h3 class="dash-title">You're viewing Clicks</h3>
    
    <form class="form-inline" action="/dashboard" method="get">
        <div class="input-daterange input-group date-range" id="datepicker">
            <input type="text" class="input-sm form-control" name="start" />
            <!--<span class="input-group-addon">to</span>-->
            <input type="text" class="input-sm form-control" name="end" />
            <button type="submit" form="datepicker" value="Submit" class="btn btn-danger navbar-btn">Go</button> 
        </form>
        
    </div>
            
 <% else %>
  <h1 class="dash-title">Nobody Logged In</h1>
 <% end %>
	<div class="row" id="graph-container">
    <div id="graph">
  	    <%= line_chart  @data, @options %>            
    </div>
    <div class="row text-center">    
        <strong>Clicks <%= check_box_tag 'Clicks', 'yes', false, class: 'clicks lead js-clicks' %></strong>
        <strong>Impressions <%= check_box_tag 'Impressions', 'yes', false, class: 'Impressions lead js-impressions' %></strong>
        <strong>Avg. CPC <%= check_box_tag 'Avg. CPC', 'yes', false, class: 'Avg. CPC lead js-cpc' %></strong>
        <strong>Cost <%= check_box_tag 'Cost', 'yes', false, class: 'Cost lead js-cost' %></strong>
        <strong>CTR <%= check_box_tag 'CTR', 'yes', false, class: 'CTR lead js-ctr' %></strong>
        <strong>Conversions <%= check_box_tag 'Conversions', 'yes', false, class: 'Conversions lead js-conversions' %></strong>
        <strong>Conversion Rate <%= check_box_tag 'Conversion Rate', 'yes', false, class: 'Conversion Rate lead js-conversion-rate' %></strong>
        <strong>CPA <%= check_box_tag 'CPA', 'yes', false, class: 'CPA lead js-cpa' %></strong>
    </div>
    <!-- 1st row of KPIs -->
	</div>
  <div class="row text-center">
    <div class="col-sm-3">
        <text class="kpi lead">clicks</text>
        <p class= "kpi-number"><strong><%= @dashboard_kpi[:clicks] %></strong></p> 
    </div>
    <div class="col-sm-3">
        <text class="kpi lead">impressions</text>
        <p class= "kpi-number"><strong><%= @dashboard_kpi[:impressions] %></strong></p>  
    </div>
    <div class="col-sm-3">
        <text class="kpi lead">ctr</text>
        <p class= "kpi-number"><strong>%<%= @dashboard_kpi[:ctr] %></strong></p> 
    </div>
    <div class="col-sm-3">
        <text class="kpi lead">cpc</text>
        <p class= "kpi-number"><strong>$<%= @dashboard_kpi[:cpc]  %></strong></p> 
    </div>
  </div>
    <!-- 2nd row of KPIs -->
    <div class="row text-center">
    <div class="col-sm-3">
          <text class="kpi lead">cost</text>
          <p class= "kpi-number">$<strong><%= @dashboard_kpi[:cost] %></strong></p> 
      </div>
      <div class="col-sm-3">
          <text class="kpi lead">cpa</text>
          <p class= "kpi-number"><strong>$<%= @dashboard_kpi[:cpa] %></strong></p>  
      </div>
      <div class="col-sm-3">
          <text class="kpi lead">conversions</text>
          <p class= "kpi-number"><strong><%= @dashboard_kpi[:conversions]  %></strong></p> 
      </div>
      <div class="col-sm-3">
          <text class="kpi lead">conv. rate</text>
          <p class= "kpi-number"><strong>%<%= @dashboard_kpi[:conv_rate]  %></strong></p> 
      </div>
    </div>
<hr>
<h2 class="dash-title"> Recommendations for this week's data: </h2>
<table class="table recommendation table-bordered">
  <tr>
    <th>Main Takeaway</th>
    <th>Recommendation</th> 
    <th>Ease of Implementation</th>
  </tr>
  <tr>
    <td><%= @cpa_recommendation[:takeaway] %></td>
    <td><%= @cpa_recommendation[:recommendation] %></td> 
    <td class="implementation"><%= @cpa_recommendation[:implementation] %></td>
  </tr>
  <tr>
    <td><%= @ctr_recommendation[:takeaway] %></td>
    <td><%= @ctr_recommendation[:recommendation] %></td> 
    <td><%= @ctr_recommendation[:implementation] %></td>
  </tr>
</table>

<h2 class="dash-title">View Other Reports:</h2>
<div class-"row">
    <div class="col-sm-4 div-container">
    <h5 class="dash-title"> Monthly SEM Report</h5>
        <%= link_to image_tag("chart-1.jpg", :class => "image-chart"), monthly_report_path %>
       </div>
    <div class="col-sm-4 div-container">
    <h5 class="dash-title"> Yearly SEM Report</h5>
        <%= link_to image_tag("chart-2.jpg", :class => "image-chart"), yearly_report_path %>
     </div>
     <div class="col-sm-4 div-container">
    <h5 class="dash-title"> Geographic Report</h5>
        <%= link_to image_tag("chart-3.jpg", :class => "image-chart"), dashboard_geo_path %>
     </div>
</div>
<div class="row">
    <div class="col-sm-12 text-center text-bottom footer">
        <div>
			<ul>
				<li class="footer-link"><%= link_to "Home", root_path %></li> |   					
				<li class="footer-link"><%= link_to "Request a Demo", new_user_registration_path %></li> |   					
				<li class="footer-link"><%= link_to "Sign In", new_user_session_path %></li> |   					
				<li class="footer-link"><%= link_to "About Us", about_us_path %></li> |   			
			</ul>		
			RERUM Data © Miami, FL USA
        </div>							
    </div>	
</div>

app/views/dashboard/dashboard_geographic.html.erb
<% if user_signed_in? %>
  <h1 class="dash-title">Hello <%= current_user.name %> Welcome to Your Dashboard:</h1>
<h3 class="dash-title">You're viewing Conversions by Geolocation</h3>
 <% else %>
  <h1 class="dash-title">Nobody Logged In</h1>
 <% end %>
	<div class="row" id="graph-container">
    <div id="graph">                        
          <%= pie_chart  @data, @options %>            
    </div>
    <div class="row text-center">    
        <strong>Clicks <%= check_box_tag 'Clicks', 'yes', false, class: 'clicks lead js-clicks' %></strong>
        <strong>Impressions <%= check_box_tag 'Impressions', 'yes', false, class: 'Impressions lead js-impressions' %></strong>
        <strong>Avg. CPC <%= check_box_tag 'Avg. CPC', 'yes', false, class: 'Avg. CPC lead js-cpc' %></strong>
        <strong>Cost <%= check_box_tag 'Cost', 'yes', false, class: 'Cost lead js-cost' %></strong>
        <strong>CTR <%= check_box_tag 'CTR', 'yes', false, class: 'CTR lead js-ctr' %></strong>
        <strong>Conversions <%= check_box_tag 'Conversions', 'yes', false, class: 'Conversions lead js-conversions' %></strong>
        <strong>Conversion Rate <%= check_box_tag 'Conversion Rate', 'yes', false, class: 'Conversion Rate lead js-conversion-rate' %></strong>
        <strong>CPA <%= check_box_tag 'CPA', 'yes', false, class: 'CPA lead js-cpa' %></strong>
    </div>
    <!-- 1st row of KPIs -->
	</div>
  <div class="row text-center">
    <div class="col-sm-3">
        <text class="kpi lead">clicks</text>
        <p class= "kpi-number"><strong><%= @dashboard_kpi[:clicks] %></strong></p> 
    </div>
    <div class="col-sm-3">
        <text class="kpi lead">impressions</text>
        <p class= "kpi-number"><strong><%= @dashboard_kpi[:impressions] %></strong></p>  
    </div>
    <div class="col-sm-3">
        <text class="kpi lead">ctr</text>
        <p class= "kpi-number"><strong>%<%= @dashboard_kpi[:ctr] %></strong></p> 
    </div>
    <div class="col-sm-3">
        <text class="kpi lead">cpc</text>
        <p class= "kpi-number"><strong>$<%= @dashboard_kpi[:cpc]  %></strong></p> 
    </div>
  </div>
    <!-- 2nd row of KPIs -->
    <div class="row text-center">
    <div class="col-sm-3">
          <text class="kpi lead">cost</text>
          <p class= "kpi-number">$<strong><%= @dashboard_kpi[:cost] %></strong></p> 
      </div>
      <div class="col-sm-3">
          <text class="kpi lead">cpa</text>
          <p class= "kpi-number"><strong>$<%= @dashboard_kpi[:cpa] %></strong></p>  
      </div>
      <div class="col-sm-3">
          <text class="kpi lead">conversions</text>
          <p class= "kpi-number"><strong><%= @dashboard_kpi[:conversions]  %></strong></p> 
      </div>
      <div class="col-sm-3">
          <text class="kpi lead">conv. rate</text>
          <p class= "kpi-number"><strong>%<%= @dashboard_kpi[:conv_rate]  %></strong></p> 
      </div>
    </div>
<hr>
<h2 class="dash-title"> Recommendations for this week's data: </h2>
<table class="table recommendation table-bordered">
  <tr>
    <th>Main Takeaway</th>
    <th>Recommendation</th> 
    <th>Ease of Implementation</th>
  </tr>
  <tr>
    <td><%= @cpa_recommendation[:takeaway] %></td>
    <td><%= @cpa_recommendation[:recommendation] %></td> 
    <td class="implementation"><%= @cpa_recommendation[:implementation] %></td>
  </tr>
  <tr>
    <td><%= @ctr_recommendation[:takeaway] %></td>
    <td><%= @ctr_recommendation[:recommendation] %></td> 
    <td><%= @ctr_recommendation[:implementation] %></td>
  </tr>
</table>

<h2 class="dash-title">View Other Reports:</h2>
<div class-"row">
    <div class="col-sm-4 div-container">
    <h5 class="dash-title"> Monthly SEM Report</h5>
        <%= link_to image_tag("chart-1.jpg", :class => "image-chart"), monthly_report_path %>
       </div>
    <div class="col-sm-4 div-container">
    <h5 class="dash-title"> Yearly SEM Report</h5>
        <%= link_to image_tag("chart-2.jpg", :class => "image-chart"), yearly_report_path %>
     </div>
     <div class="col-sm-4 div-container">
    <h5 class="dash-title"> Geographic Report</h5>
        <%= link_to image_tag("chart-3.jpg", :class => "image-chart"), dashboard_geo_path %>
     </div>
</div>
<div class="row">
    <div class="col-sm-12 text-center text-bottom footer">
        <div>
			<ul>
				<li class="footer-link"><%= link_to "Home", root_path %></li> |   					
				<li class="footer-link"><%= link_to "Request a Demo", new_user_registration_path %></li> |   					
				<li class="footer-link"><%= link_to "Sign In", new_user_session_path %></li> |   					
				<li class="footer-link"><%= link_to "About Us", about_us_path %></li> |   			
			</ul>		
			RERUM Data © Miami, FL USA
        </div>							
    </div>	
</div>

app/views/dashboard/dashboard_test.html.erb
<% if user_signed_in? %>
  <h1 class="dash-title">Hello <%= current_user.name %>, This is an example Dashboard:</h1>
  <h3 class="dash-title">You've just gained easy insights on your data. We will contact you shortly</h3>
  <h4 class="dash-title">Feel free to look around</h3>
 <% else %>
  <h1 class="dash-title">Nobody Logged In</h1>
 <% end %>
	<div class="row" id="graph-container">
    <div id="graph">
  	    <%= line_chart  @data, @options %>            
    </div>

    <div class="row text-center">    
        <strong>Clicks <%= check_box_tag 'Clicks', 'yes', false, class: 'clicks lead' %></strong>
        <strong>Impressions <%= check_box_tag 'Impressions', 'yes', false, class: 'Impressions lead' %></strong>
        <strong>Avg. CPC <%= check_box_tag 'Avg. CPC', 'yes', false, class: 'Avg. CPC lead' %></strong>
        <strong>Cost <%= check_box_tag 'Cost', 'yes', false, class: 'Cost lead' %></strong>
        <strong>CTR <%= check_box_tag 'CTR', 'yes', false, class: 'CTR lead' %></strong>
        <strong>Conversions <%= check_box_tag 'Conversions', 'yes', false, class: 'Conversions lead' %></strong>
        <strong>Conversion Rate <%= check_box_tag 'Conversion Rate', 'yes', false, class: 'Conversion Rate lead' %></strong>
        <strong>CPA <%= check_box_tag 'CPA', 'yes', false, class: 'CPA lead' %></strong>
    </div>
   
	</div>
  <div class="row text-center">
    <div class="col-sm-3">
        <text class="kpi lead">clicks</text>
        <p class= "kpi-number"><strong> 1,100 </strong></p> 
    </div>
    <div class="col-sm-3">
        <text class="kpi lead">impressions</text>
        <p class= "kpi-number"><strong>1,100</strong></p>  
    </div>
    <div class="col-sm-3">
        <text class="kpi lead">ctr</text>
        <p class= "kpi-number"><strong>5.15%</strong></p> 
    </div>
    <div class="col-sm-3">
        <text class="kpi lead">cpc</text>
        <p class= "kpi-number">$<strong>14.50</strong></p> 
    </div>
  </div>
    
    <div class="row text-center">
    <div class="col-sm-3">
          <text class="kpi lead">cost</text>
          <p class= "kpi-number">$<strong>3,000<strong></p> 
      </div>
      <div class="col-sm-3">
          <text class="kpi lead">cpa</text>
          <p class= "kpi-number">$<strong>20</strong></p>  
      </div>
      <div class="col-sm-3">
          <text class="kpi lead">conversions</text>
          <p class= "kpi-number"><strong>23</strong></p> 
      </div>
      <div class="col-sm-3">
          <text class="kpi lead">conv. rate</text>
          <p class= "kpi-number"><strong> 2.3% </strong></p> 
      </div>
    </div>
<hr>
<h2 class="dash-title"> Recommendations for this week's data: </h2>
	<table class="table recommendation table-bordered">
        <tr>
            <th class="text-center">Main Takeaway</th>
            <th class="text-center">Recommendation</th> 
            <th class="text-center">Ease of Implementation</th>
        </tr>
        <tr>
            <td>Avg. CPC has been increasing greatly in the last few days</td>
            <td>Perhaps Competitors are bidding more aggresively</td> 
            <td class="easy">Easy</td>
        </tr>
        <tr>
            <td>Campaign "Shoes" Conversions has increased significantly in the last few days</td>
            <td>Opportunity to increase CPC's for top converting Keywords</td> 
            <td class="medium">Medium</td>
        </tr>
        <tr>
            <td>Overall CTR has decreased significantly</td>
            <td>Perform Search Query Reports</td> 
            <td class="hard">Hard</td>
        </tr>
    </table>

<h2 class="dash-title">View Other Reports:</h2>
<div class-"row">
    <div class="col-sm-4 div-container">
    <h5 class="dash-title"> Monthly SEM Report</h5>
        <%= link_to image_tag("chart-1.jpg", :class => "image-chart"), monthly_report_path %>
       </div>
    <div class="col-sm-4 div-container">
    <h5 class="dash-title"> Yearly SEM Report</h5>
        <%= link_to image_tag("chart-2.jpg", :class => "image-chart"), yearly_report_path %>
     </div>
     <div class="col-sm-4 div-container">
    <h5 class="dash-title"> Geographic Report</h5>
        <%= link_to image_tag("chart-3.jpg", :class => "image-chart"), dashboard_geo_path %>
     </div>
</div>
<div class="row">
    <div class="col-sm-12 text-center text-bottom footer">
        <div>
			<ul>
				<li class="footer-link"><%= link_to "Home", root_path %></li> |   					
				<li class="footer-link"><%= link_to "Request a Demo", new_user_registration_path %></li> |   					
				<li class="footer-link"><%= link_to "Sign In", new_user_session_path %></li> |   					
				<li class="footer-link"><%= link_to "About Us", about_us_path %></li> |   			
			</ul>		
			RERUM Data © Miami, FL USA
        </div>							
    </div>	
</div>