config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations' }
root to: 'static_pages#home'
get '/about-us' => 'static_pages#about_us'


# dashboard
get '/dashboard' => 'dashboard#dashboard'
get '/dashboard-test' => 'dashboard#dashboard_test'
get '/yearly-report' => 'dashboard#yearly_report'
get '/monthly-report' => 'dashboard#monthly_report'
get '/weekly-dashboard-impressions' => 'dashboard#weekly_dashboard_impressions'
get '/weekly-dashboard-cost' => 'dashboard#weekly_dashboard_cost'
get '/weekly-dashboard-conversions' => 'dashboard#weekly_dashboard_conversions'
get '/weekly-dashboard-ctr' => 'dashboard#weekly_dashboard_ctr'
get '/weekly-dashboard-conversion-rate' => 'dashboard#weekly_dashboard_conversion_rate'
get '/weekly-dashboard-cpa' => 'dashboard#weekly_dashboard_cpa'
get '/weekly-dashboard-cpc' => 'dashboard#weekly_dashboard_cpc'
get '/dashboard-geo' => 'dashboard#dashboard_geographic'


get "login/prompt"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script> 
<script src="https://code.jquery.com/jquery-3.1.1.min.js" integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=" crossorigin="anonymous"></script>
    <title>Rerum</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <!-- investigate about this and do an if to when this is triggering -->
	<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">
      <%= link_to(image_tag("logodieter.png", :class => "navbar-logo navbar-btn"), root_path) %>
      <!-- <%= image_tag("logodieter.png", :class => "navbar-logo") %> -->
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="/about-us">About Us</a></li> 
        
      </ul>
      <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li><%= button_to "Dashboard", dashboard_path, :method => :get,  :class => "btn btn-warning navbar-btn" %></li>
        <li><%= button_to "Logout", destroy_user_session_path, :method => :delete, :class => "btn btn-danger navbar-btn" %></li>

        <% else%>
        <li><%= button_to "Request a Demo", new_user_registration_path, :method => :get,  :class => "btn btn-primary navbar-btn" %></li>
        <li><%= button_to "Sign In", new_user_session_path, :class => "btn btn-success navbar-btn" %></li>
          <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    
  </body>
</html>

<!-- 
<button type="button" class="btn btn-default">Default</button>
 -->